# Generated by Django 4.2.7 on 2026-06-14 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='计划标题')),
                ('plan_type', models.CharField(choices=[('diet', '饮食计划'), ('sport', '运动计划'), ('body', '体征管理'), ('comprehensive', '综合计划')], max_length=50, verbose_name='计划类型')),
                ('target_value', models.CharField(blank=True, max_length=100, null=True, verbose_name='目标值')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('status', models.SmallIntegerField(choices=[(0, '进行中'), (1, '已完成'), (2, '已放弃')], default=0, verbose_name='状态')),
                ('description', models.TextField(blank=True, null=True, verbose_name='计划描述')),
                ('reminder', models.BooleanField(default=False, verbose_name='是否提醒')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_plans', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '健康计划',
                'verbose_name_plural': '健康计划',
                'db_table': 'health_plan_healthplan',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['user', 'status'], name='health_plan_user_id_135a82_idx')],
            },
        ),
    ]
