# Generated by Django 4.2.7 on 2026-06-17 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health_plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField(default=django.utils.timezone.now, verbose_name='打卡日期')),
                ('checkin_time', models.DateTimeField(auto_now_add=True, verbose_name='打卡时间')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='health_plan.healthplan', verbose_name='计划')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_checkins', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '计划打卡',
                'verbose_name_plural': '计划打卡',
                'db_table': 'health_plan_checkin',
                'ordering': ['-checkin_time'],
                'indexes': [models.Index(fields=['plan', 'checkin_date'], name='health_plan_plan_id_342d07_idx'), models.Index(fields=['user', 'checkin_date'], name='health_plan_user_id_929d12_idx')],
                'unique_together': {('plan', 'checkin_date')},
            },
        ),
    ]
