# Generated by Django 4.2.7 on 2026-06-14 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手')], max_length=20, verbose_name='角色')),
                ('message', models.TextField(verbose_name='消息内容')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='会话ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'AI对话历史',
                'verbose_name_plural': 'AI对话历史',
                'db_table': 'ai_chat_chathistory',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['user', 'session_id'], name='ai_chat_cha_user_id_b74445_idx'), models.Index(fields=['created_at'], name='ai_chat_cha_created_f1fe9e_idx')],
            },
        ),
    ]
