# Generated by Django 4.2.7 on 2026-06-14 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '资讯分类',
                'verbose_name_plural': '资讯分类',
                'db_table': 'health_news_newscategory',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news/%Y/%m/', verbose_name='封面图片')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='摘要')),
                ('content', models.TextField(verbose_name='内容')),
                ('author', models.CharField(blank=True, max_length=50, null=True, verbose_name='作者')),
                ('source', models.CharField(blank=True, max_length=100, null=True, verbose_name='来源')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览量')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='health_news.newscategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '健康资讯',
                'verbose_name_plural': '健康资讯',
                'db_table': 'health_news_news',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['category', 'is_published'], name='health_news_categor_67a457_idx'), models.Index(fields=['published_at'], name='health_news_publish_3586b5_idx')],
            },
        ),
    ]
