# Generated by Django 4.2.7 on 2026-06-14 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type', models.CharField(max_length=50, verbose_name='运动类型')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='运动时长(分钟)')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='距离(km)')),
                ('calories', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='消耗热量(kcal)')),
                ('steps', models.IntegerField(blank=True, null=True, verbose_name='步数')),
                ('sport_date', models.DateField(verbose_name='运动日期')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '运动记录',
                'verbose_name_plural': '运动记录',
                'db_table': 'health_record_sportrecord',
                'ordering': ['-sport_date'],
                'indexes': [models.Index(fields=['user', 'sport_date'], name='health_reco_user_id_8454d6_idx')],
            },
        ),
        migrations.CreateModel(
            name='DietRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', '早餐'), ('lunch', '午餐'), ('dinner', '晚餐'), ('snack', '加餐')], max_length=20, verbose_name='餐别')),
                ('food_name', models.CharField(max_length=200, verbose_name='食物名称')),
                ('calories', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='热量(kcal)')),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='蛋白质(g)')),
                ('fat', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='脂肪(g)')),
                ('carbohydrate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='碳水化合物(g)')),
                ('portion_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='份量')),
                ('record_datetime', models.DateTimeField(verbose_name='记录时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_records', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '饮食记录',
                'verbose_name_plural': '饮食记录',
                'db_table': 'health_record_dietrecord',
                'ordering': ['-record_datetime'],
                'indexes': [models.Index(fields=['user', 'record_datetime'], name='health_reco_user_id_76757f_idx')],
            },
        ),
        migrations.CreateModel(
            name='BodyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='体重(kg)')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='身高(cm)')),
                ('blood_pressure_systolic', models.IntegerField(blank=True, null=True, verbose_name='收缩压(mmHg)')),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, null=True, verbose_name='舒张压(mmHg)')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='心率(次/分)')),
                ('blood_sugar', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='血糖(mmol/L)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='体温(℃)')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_data', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '体征数据',
                'verbose_name_plural': '体征数据',
                'db_table': 'health_record_bodydata',
                'ordering': ['-record_date'],
                'indexes': [models.Index(fields=['user', 'record_date'], name='health_reco_user_id_dce217_idx')],
            },
        ),
    ]
